pretend to log error to default.error.log: Error: Fail whale failed. :-(
configurable-error-logger logged 1 errors.
/…/node_modules/p-fatal/fatal.js:…
  setImmediate(function rethrowNow() { throw e; });
                                       ^

<ref *1> Error: Fail whale failed. :-(
    at failWhale (…/why.js:…:…)
    at Object.<anonymous> (…/why.js:…:…)
    at Generator.next (<anonymous>) {
  promise: Promise { <rejected> [Circular *1] }
}
